on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: pnpm
              uses: pnpm/action-setup@v2
              with:
                version: 8
            - name: node
              uses: actions/setup-node@v3
              with:
                node-version: latest
            - name: Server dependencies
              run: pnpm i
              working-directory: ./Server
            - name: Web dependencies
              run: pnpm i
              working-directory: ./Web
            - name: Build
              run: pnpm buildRelease
              working-directory: ./Server
              env:
                SKIP_ZIP: 1
            - name: Artifact
              uses: actions/upload-artifact@v3
              with:
                name: BurgerPanel.zip
                path: Server/_build/
